name: ATLAS Maestro CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Despliegue Directo (Self-Hosted)
    runs-on: self-hosted
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Llave SSH Interna
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_key
          chmod 600 ~/.ssh/github_key
          ssh-keyscan -H ${{ secrets.SERVER_WEB_IP }} >> ~/.ssh/known_hosts

      - name: Desplegar Frontend (Hacia srv-cpan01)
        run: |
          scp -i ~/.ssh/github_key -r frontend/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_WEB_IP }}:/var/www/dashboard/
          ssh -i ~/.ssh/github_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_WEB_IP }} "sudo /bin/chmod 644 /var/www/dashboard/*"

      - name: Desplegar Backend (Local en srvu-cpan03)
        run: |
          cp -r backend/* /opt/api-ircnl/
          echo "${{ secrets.ENV_PRODUCTION }}" > /opt/api-ircnl/.env
          sudo /bin/chmod 600 /opt/api-ircnl/.env
          cd /opt/api-ircnl/
          npm install --production
	  pm2 restart api-ircnl --update-env
          pm2 save
